nome = str(input('Digite seu nome completo: '))
nome_lista = nome.split()
print('Muito prazer em te conhecer.')
print(f'O seu primeiro nome é {nome_lista[0]}')
print(f'O seu último nome é {nome_lista[-1]}')
